### ISSUE TITLE
Alchemy intersection overlay isn't working

### ISSUE THREAD

**Issue by Coaltown992** [vartan/abc-alch#4]
Can't say why but at some point the intersection overlay stopped showing up. I tried resetting the settings and reinstalling the add on.

**Comment by GeraltOfNivea2** [comment]
same issue

**Comment by TheGoldenCloudx** [comment]
I'm running into the same issue

**Comment by vartan** [comment]
Thanks for reporting this! I suspect this broke around the time they split out the enchantments into their own sub-interface.

I will try to resolve this soon, it may take me an extra day or two since I haven't set up my development environment on this new laptop.

**Comment by vartan** [comment]
I have fixed this bug with [this commit](https://github.com/vartan/abc-alch/commit/f72d00e4646c7a4b1b96dd3728de955c0e0c0b82), awaiting RuneLite to pull in the newest version.

**Comment by vartan** [comment]
It looks like some of the APIs used are deprecated now, reopening this until that is fixed. Thank you for your patience.

**Comment by vartan** [comment]
I resolved the deprecated API usage last night, once again awaiting RuneLite to accept the plugin changes.

**Comment by vartan** [comment]
Fix is live!! thanks again for reporting the issue, I will try to address any breaking changes faster in the future.
